<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions
		name="ModtagFinansbilagStraksleveranceService"
		targetNamespace="urn:oio:kl:kdi:oir:1590_A_V2"
		xmlns:oir="urn:oio:kl:kdi:oir:1590_A_V2"
		xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
		xmlns:xsd="http://www.w3.org/2001/XMLSchema"
		xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
		xmlns:wsp="http://www.w3.org/ns/ws-policy"
		xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
		xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata"
		xmlns:spf="http://serviceplatformen.dk/xml/schemas/ServiceplatformFault/1/"
		xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702">
	<wsdl:types>
		<xsd:schema targetNamespace="urn:oio:kl:kdi:oir:1590_A_V2">
			<xsd:include schemaLocation="ModtagFinansbilagStraksleveranceServiceMsg.xsd"/>
			<xsd:include schemaLocation="view/FinansStraksleveranceTransportkvittering.xsd" />
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="FinansbilagRequestMessage">
		<wsdl:part name="request" element="oir:FinansbilagRequestType"/>
	</wsdl:message>
	<wsdl:message name="FinansbilagResponseMessage">
		<wsdl:part name="response" element="oir:FinansbilagResponseType"/>
	</wsdl:message>
	<wsdl:message name="StraksleveranceTransportkvittering">
		<wsdl:part name="fault" element="oir:StraksleveranceTransportkvittering"/>
	</wsdl:message>


	<wsdl:portType name="ModtagFinansbilagStraksleveranceServicePort">
		<wsdl:operation name="Straksleverance">
			<wsdl:input message="oir:FinansbilagRequestMessage"/>
			<wsdl:output message="oir:FinansbilagResponseMessage"/>
			<wsdl:fault name="StraksleveranceTransportkvittering" message="oir:StraksleveranceTransportkvittering"/>
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="ModtagFinansbilagStraksleveranceServiceBinding" type="oir:ModtagFinansbilagStraksleveranceServicePort">
		<wsp:PolicyReference URI="#TransportbindingPolicy"/>
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document" />
		<wsdl:operation name="Straksleverance">
            <wsp:PolicyReference URI="#TokenBindingPolicy"/>
            <soap:operation soapAction=""/>
            <wsdl:input>
                <wsp:PolicyReference URI="#Input_Policy" />
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
			<wsdl:fault name="StraksleveranceTransportkvittering">
				<soap:fault name="StraksleveranceTransportkvittering" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="ModtagFinansbilagStraksleveranceService">
		<wsdl:port name="ModtagFinansbilagStraksleveranceServicePort" binding="oir:ModtagFinansbilagStraksleveranceServiceBinding">
			<soap:address location="http://localhost:8080/service/OiRFinans/1"/>
		</wsdl:port>
	</wsdl:service>

	<wsp:Policy wsu:Id="TransportbindingPolicy">
        <sp:TransportBinding xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702">
            <wsp:Policy>
                <sp:TransportToken>
                    <wsp:Policy>
                        <sp:HttpsToken RequireClientCertificate="true"/>
                    </wsp:Policy>
                </sp:TransportToken>
                <sp:AlgorithmSuite>
                    <wsp:Policy>
                        <sp:Basic256/>
                    </wsp:Policy>
                </sp:AlgorithmSuite>
            </wsp:Policy>
        </sp:TransportBinding>
    </wsp:Policy>

    <wsp:Policy wsu:Id="TokenBindingPolicy">
        <wsp:ExactlyOne>
            <wsp:All>
                <wsam:Addressing wsp:Optional="false">
                    <wsp:Policy/>
                </wsam:Addressing>
                <sp:AsymmetricBinding>
                    <wsp:Policy>

                        <sp:InitiatorToken>
                            <wsp:Policy>
                                <sp:SamlToken sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Never">
                                    <wsp:Policy>
                                        <sp:WssSamlV20Token11/>
                                    </wsp:Policy>
                                </sp:SamlToken>
                            </wsp:Policy>
                        </sp:InitiatorToken>

                        <sp:RecipientToken>
                            <wsp:Policy>
                                <sp:X509Token sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToInitiator">
                                    <wsp:Policy>
                                        <sp:WssX509V3Token10/>
                                    </wsp:Policy>
                                </sp:X509Token>
                            </wsp:Policy>
                        </sp:RecipientToken>

                        <sp:AlgorithmSuite>
                            <wsp:Policy>
                                <sp:Basic256/>
                            </wsp:Policy>
                        </sp:AlgorithmSuite>

                        <sp:Layout>
                            <wsp:Policy>
                                <sp:Strict/>
                            </wsp:Policy>
                        </sp:Layout>

                        <sp:ProtectTokens/>
                        <sp:IncludeTimestamp/>
                        <sp:OnlySignEntireHeadersAndBody/>
                    </wsp:Policy>
                </sp:AsymmetricBinding>

                <sp:SignedSupportingTokens xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702">
                    <wsp:Policy>
                        <sp:IssuedToken sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                            <sp:RequestSecurityTokenTemplate/>
                            <wsp:Policy>
                                <sp:WssSamlV20Token11/>
                            </wsp:Policy>
                        </sp:IssuedToken>
                    </wsp:Policy>
                </sp:SignedSupportingTokens>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>

    <!-- Input policy for signing input -->
    <wsp:Policy wsu:Id="Input_Policy">
        <wsp:ExactlyOne>
            <wsp:All>
                <sp:SignedParts>
                    <sp:Body/>
                    <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing"/>
                    <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing"/>
                    <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing"/>
                    <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing"/>
                    <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing"/>
                    <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing"/>
                    <sp:Header Name="Framework" Namespace="urn:liberty:sb:2006-08"/>
                </sp:SignedParts>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>

	<xsd:annotation>
		<xsd:documentation xml:lang="en">
			Version 1.0 of the API for the ModtagFinansbilagService
    	</xsd:documentation>
	</xsd:annotation>
</wsdl:definitions>
